/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pack_gui;
import pack_gui.frmlogin;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class frmregistro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmregistro.class.getName());
    private HashMap<String, String> mapaUsuarios = new HashMap<>();
    /**
     * Creates new form frmregistro
     */
    public frmregistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pRegistro = new javax.swing.JPanel();
        lRegistro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cTipoUsuario = new javax.swing.JComboBox<>();
        bRegistrarUsuario = new javax.swing.JButton();
        pContrasena1 = new javax.swing.JPasswordField();
        tApellido = new javax.swing.JTextField();
        tNombre = new javax.swing.JTextField();
        iRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pRegistro.setBackground(new java.awt.Color(153, 102, 255));
        pRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lRegistro.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        lRegistro.setText("REGISTRO");
        pRegistro.add(lRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, -1));

        jButton1.setText("Volver");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(this::jButton1ActionPerformed);
        pRegistro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        cTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Paciente", "Doctor", "Farmaceutico" }));
        cTipoUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Usuario"));
        cTipoUsuario.addActionListener(this::cTipoUsuarioActionPerformed);

        bRegistrarUsuario.setBackground(new java.awt.Color(204, 204, 255));
        bRegistrarUsuario.setText("REGISTRAR USUARIO");
        bRegistrarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bRegistrarUsuarioMouseClicked(evt);
            }
        });
        bRegistrarUsuario.addActionListener(this::bRegistrarUsuarioActionPerformed);

        pContrasena1.setText("jPasswordField1");
        pContrasena1.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));

        tApellido.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));

        tNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));
        tNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tNombreMouseClicked(evt);
            }
        });
        tNombre.addActionListener(this::tNombreActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bRegistrarUsuario)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(tNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pContrasena1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bRegistrarUsuario)
                .addGap(21, 21, 21))
        );

        pRegistro.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 390, 280));

        iRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo_hospital.png"))); // NOI18N
        pRegistro.add(iRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 490, 350));

        getContentPane().add(pRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarEnCSV(){
        try (java.io.FileWriter fw = new java.io.FileWriter("usuarios.csv");
            java.io.PrintWriter pw = new java.io.PrintWriter(fw)) {
        
                pw.println("Usuario,Contrasena");
        
                for (java.util.Map.Entry<String, String> entry : mapaUsuarios.entrySet()) {
                    pw.println(entry.getKey() + "," + entry.getValue());
                }
        
                javax.swing.JOptionPane.showMessageDialog(this, "Usuario registrado y base de datos actualizada.");
        } catch (java.io.IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar archivo: " + e.getMessage());
        }
    }
    
    private void cTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTipoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cTipoUsuarioActionPerformed

    private void bRegistrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegistrarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRegistrarUsuarioActionPerformed

    private void tNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreActionPerformed

    private void bRegistrarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegistrarUsuarioMouseClicked

        String nombre = tNombre.getText().trim();
        String apellido = tApellido.getText().trim();
        String tipo = cTipoUsuario.getSelectedItem().toString();
        String password = pContrasena1.getPassword().toString(); 

        if (nombre.isEmpty() || apellido.isEmpty() || password.isEmpty() || tipo.equals("Seleccionar")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
            return;
        }

        String usuarioID = (nombre.substring(0, 1) + "." + apellido + "_" + tipo + "@gestionmedica.gob.ec").toLowerCase();

        mapaUsuarios.put(usuarioID, password);

        guardarEnCSV();
    
        tNombre.setText("");
        tApellido.setText("");
        pContrasena1.setText("");
        cTipoUsuario.setSelectedIndex(0);
    }//GEN-LAST:event_bRegistrarUsuarioMouseClicked

    private void tNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tNombreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tNombreMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        frmlogin ventanaLogin = new frmlogin(); 
        ventanaLogin.setVisible(true); 
        ventanaLogin.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new frmregistro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRegistrarUsuario;
    private javax.swing.JComboBox<String> cTipoUsuario;
    private javax.swing.JLabel iRegistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lRegistro;
    private javax.swing.JPasswordField pContrasena1;
    private javax.swing.JPanel pRegistro;
    private javax.swing.JTextField tApellido;
    private javax.swing.JTextField tNombre;
    // End of variables declaration//GEN-END:variables
}